version: '3'

services:
  
 
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/_data/postgres:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8

  api: 
    build: .
    image: drf-api:latest
    container_name: drf-api
    restart: always
    command: ["uwsgi", "--ini", "/app/uwsgi.ini"]
    env_file: .env
    tty: true
    environment:
      - HTTP_PORT=8015
      - STATS_PORT=8001
      - DEBUG=True
      - POSTGRES_HOST=postgres
    volumes:
      - ${PWD}/app:/app
    ports:
      - 8015:8015
    depends_on:
      - postgres
  
 