CREATE USER test WITH PASSWORD 'test' CREATEDB;
CREATE DATABASE test
    WITH 
    OWNER = test
    ENCODING = 'UTF8'
    LC_COLLATE = 'C.UTF-8'
    LC_CTYPE = 'C.UTF-8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;