# Generated by Django 3.2 on 2021-04-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
